package me.goosbanny.goosboards.command.subcommand;

import me.goosbanny.goosboards.command.BoardSelectionManager;
import me.goosbanny.goosboards.command.CommandUtils;
import me.goosbanny.goosboards.command.SubCommand;
import me.goosbanny.goosboards.config.ConfigReloadManager;
import me.goosbanny.goosboards.core.logging.MessageService;
import me.goosbanny.goosboards.raycast.Vector3d;
import org.bukkit.command.CommandSender;
import org.bukkit.entity.Player;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.Map;
import java.util.Objects;
import java.util.UUID;

/**
 * Handles /gb create [name].
 */
public class CreateSubCommand implements SubCommand {

    private final ConfigReloadManager reloadManager;
    private final BoardSelectionManager selectionManager;
    private final MessageService messageService;
    private final File boardsFolder;

    public CreateSubCommand(
            ConfigReloadManager reloadManager,
            BoardSelectionManager selectionManager,
            MessageService messageService,
            File boardsFolder
    ) {
        this.reloadManager = Objects.requireNonNull(reloadManager, "reloadManager");
        this.selectionManager = Objects.requireNonNull(selectionManager, "selectionManager");
        this.messageService = Objects.requireNonNull(messageService, "messageService");
        this.boardsFolder = Objects.requireNonNull(boardsFolder, "boardsFolder");
    }

    @Override
    public String getName() {
        return "create";
    }

    @Override
    public void execute(CommandSender sender, String label, String[] args) {
        if (!(sender instanceof Player player)) {
            messageService.send(sender, "selection-player-only");
            return;
        }

        UUID uuid = player.getUniqueId();

        if (args.length == 0 || args[0].startsWith("-")) {
            BoardSelectionManager.SelectionSession existing = selectionManager.getSession(uuid);
            if (existing != null) {
                messageService.send(sender, "selection-already-active", Map.of("label", label));
            } else {
                selectionManager.startSession(uuid);
                messageService.send(sender, "selection-started");
            }
            return;
        }

        String boardName = CommandUtils.sanitizeBoardName(args[0]);
        if (boardName.isBlank()) {
            messageService.send(sender, "board-create-failed", Map.of("error", "Invalid board name."));
            return;
        }

        BoardSelectionManager.SelectionSession session = selectionManager.getSession(uuid);
        if (session == null || session.getCorner1() == null || session.getCorner2() == null) {
            messageService.send(sender, "selection-incomplete", Map.of("label", label));
            return;
        }

        BoardSelectionManager.SelectionGeometry geo = selectionManager.computeGeometry(
                session.getCorner1(), session.getCorner2()
        );
        if (geo == null) {
            messageService.send(sender, "selection-world-mismatch");
            return;
        }

        File boardFile = new File(boardsFolder, boardName + ".yml");
        File yamlFile = new File(boardsFolder, boardName + ".yaml");
        if (boardFile.exists() || yamlFile.exists()) {
            messageService.send(sender, "board-already-exists", Map.of("board", boardName));
            return;
        }

        try {
            writeBoardTemplate(boardFile, boardName, geo);
        } catch (IOException e) {
            messageService.send(sender, "board-create-failed", Map.of("error", e.getMessage() != null ? e.getMessage() : "IO error"));
            return;
        }

        selectionManager.finalizeSession(uuid);
        reloadManager.reload();

        messageService.send(sender, "board-created", Map.of(
                "board", boardName,
                "width", String.valueOf(geo.widthBlocks()),
                "height", String.valueOf(geo.heightBlocks()),
                "dir", geo.directionLabel()
        ));
        messageService.sendActionBar(player, "board-created-actionbar", Map.of("board", boardName));
    }

    private void writeBoardTemplate(File file, String boardName, BoardSelectionManager.SelectionGeometry geo) throws IOException {
        Vector3d tl = geo.topLeft();
        try (PrintWriter pw = new PrintWriter(new FileWriter(file))) {
            pw.println("# GoosBoards - " + boardName);
            pw.println("# Auto-generated by /gb create");
            pw.println();
            pw.println("settings:");
            pw.println("  dithering: true");
            pw.println("  reset-on-radius-exit: true");
            pw.println();
            pw.println("displays:");
            pw.println("  main:");
            pw.println("    world: \"" + geo.world() + "\"");
            pw.printf("    width: %d%n", geo.widthBlocks());
            pw.printf("    height: %d%n", geo.heightBlocks());
            pw.println("    top-left:");
            pw.printf("      x: %.1f%n", tl.x());
            pw.printf("      y: %.1f%n", tl.y());
            pw.printf("      z: %.1f%n", tl.z());
            pw.println("    direction: \"" + geo.directionLabel() + "\"");
            pw.println("    distance: 32.0");
            pw.println("    interaction-distance: 16.0");
            pw.println();
            pw.println("scenes:");
            pw.println("  default:");
            pw.println("    background:");
            pw.println("      type: background");
            pw.println("      position: \"0 0\"");
            pw.println("      size: \"100% 100%\"");
            pw.println("      color: \"#1a1a2e\"");
            pw.println("    welcome:");
            pw.println("      type: text");
            pw.println("      position: \"50% 50%\"");
            pw.println("      alignment: center");
            pw.println("      vertical-alignment: center");
            pw.println("      text: \"<gradient:#3B82F6:#8B5CF6><b>" + boardName + "</b></gradient>\"");
            pw.println("      font: \"SansSerif\"");
            pw.println("      font-size: 32");
        }
    }
}
